---
- name: Install dhcp-server package
  dnf:
    name: dhcp-server
    state: latest

- name: copy dhcpd.conf
  copy:
    src: ./dhcpd.conf
    dest: /etc/dhcp/dhcpd.conf

- name: Disable dhcpd service (for debug)
  systemd:
    name: dhcpd
    state: stopped
    enabled: no