---
- name: Install unbound package
  dnf:
    name: unbound
    state: present

- name: Allow dns service for internal zone
  firewalld:
    zone: internal
    service: dns
    permanent: true
    state: enabled
    immediate: true
