---
- name: Allow ntp service for internal zone
  firewalld:
    zone: internal
    service: ntp
    permanent: true
    state: enabled
    immediate: true

- name: Copy chrony.conf
  copy:
    src: ./chrony.conf
    dest: /etc/chrony.conf
    backup: true
    mode: '0644'
  notify:
    - Restart chronyd
