---
- name: install epel-release
  dnf:
    name:
      - epel-release
    state: latest

- name: install dnf packages
  dnf:
    name:
      - bind-utils
      - iperf3
      - git
      - python3-pip
      - traceroute
      - tcpdump
      - nmap
      - whois
    state: latest

# set eth0 internal
# because https://github.com/ansible/ansible/issues/41738 , can't user firewalld module
- name: set eth0 internal
  command: "firewall-cmd --zone=internal --permanent --add-interface=eth0"

- name: reload firewalld
  command: "firewall-cmd --reload"

# set eth1 public
- name: set eth1 public
  firewalld:
    zone: public
    interface: eth1
    permanent: yes
    state: enabled
    immediate: yes

# set firewall rule

- name: deny service for public zone
  firewalld:
    zone: public
    service: "{{ item }}"
    permanent: yes
    state: disabled
    immediate: yes
  with_items:
    - cockpit
    - ssh

# masquerade
- name: set masquerade both internal, public
  firewalld:
    zone: "{{ item }}"
    masquerade: yes
    permanent: yes
    state: enabled
    immediate: yes
  with_items:
    - internal
    - public
